<template>
  <div class="content">
    <scroll>
      <ul>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
        <li>人员信息</li>
      </ul>
    </scroll>
  </div>
</template>

<script>
import Scroll from 'components/common/scroll/Scroll'
export default {
name:'Profile',
components:{
  Scroll
}
}
</script>

<style scoped>
.content{
  background-color: red;
  height: 100px;
  overflow: hidden;
}
</style>>

</style>